### ISSUE TITLE
RAW Board manager files have disappeared

### ISSUE THREAD

**Issue by palmerr23** [stm32duino/BoardManagerFiles#33]
Arduino gave this message today:

Error downloading https://github.com/stm32duino/BoardManagerFiles/raw/master/package_stmicroelectronics_index.json

The /STM32 and /STM8 files are still there, but not the /raw folder.

**Comment by fpistm** [comment]
Hi @palmerr23 
This is normal as all repositories from STM32duino organization have switched to branch name "main" as default branch name instead of "master".
https://www.stm32duino.com/viewtopic.php?f=37&t=1316

Anyway, based on this article:
https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/

 I thought it was redirect. When tested after the naming change, it was OK but probably a cache issue.
I will add a master branch  and set the index json as deprecated to warn user.

**Comment by fpistm** [comment]
Fixed by 
https://github.com/stm32duino/BoardManagerFiles/commit/7b900e45dfa71652a68a8f22c72fcda5a0c92580
