### ISSUE TITLE
Programming Nucleo F302R8

### ISSUE THREAD

**Issue by bmitov** [stm32duino/BoardManagerFiles#8]
Hello everyone,
I am trying to program Blink on Nucleo F302R8.
It seems to upload successfully:

STM32 ST-LINK CLI v3.0.0.0
STM32 ST-LINK Command Line Interface

ST-LINK SN : 066EFF495056805087162434
ST-LINK Firmware version : V2J22M5
Connected via SWD.
SWD Frequency = 4000K.
Target voltage = 3.2 V.
Connection mode : Normal.
Device ID:0x439 
Device flash Size : 64 Kbytes
Device family :STM32F301x4-x6-x8/F302x4-x6-x8/F318xx

Loading file...
Flash Programming:
  File : C:\Users\mitov\AppData\Local\Temp\arduino_build_882600\Blink.ino.bin
  Address : 0x08000000
Memory programming...
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±± 0%
 0%ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ 100%
Memory programmed in 0s and 609ms.
Programming Complete.

MCU Reset.

run application to exit
Application started.

However there is no blinking :-( . I tried PA5, D13 and 13 as LED pins. None of them works :-(
Any suggestions?
I used the - STM Nucleo F303RE (STLink).

**Comment by fpistm** [comment]
Hi @bmitov,
Nucleo F302R8 is not supported at this time.
The pins mapping is not the same than the Nucleo F303RE.
F303RE LED is connected on PA5, you are right but on F302R8 it is connected on PB13.
Moreover the linkerscript file and system clock config could differs.
That's why it is not blinking.

P.S.: please for any issue around cores submit issue on the related github. For this one: [Arduino_Core_STM32/issues](https://github.com/stm32duino/Arduino_Core_STM32/issues)
This one is mainly for installation issue thanks the BoardsManager.
