### ISSUE TITLE
Urgently need Blue Pill support

### ISSUE THREAD

**Issue by dackley1935** [stm32duino/BoardManagerFiles#9]
I'm presenting "How Program STM32F103C8/Blue Pill Using Arduino IDE" next Saturday (Sept 16)  to the Dallas Personal Robotics Group (dprg.org) where I had planned to demonstrate installing the STM32F1 cores package that supports the Blue Pill.

My problem is that the STM32F1 cores package is no longer available and the STM32 cores package doesn't yet support the Blue Pill.

**Comment by fpistm** [comment]
Hi, @dackley1935,
You can use the previous commit of the json file  which includes the old STM32F1 core 

> https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/d1c46284dec37305d563a87eecfb545e3c66a166/STM32/package_stm_index.json

instead of 

> https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

 in  _Preference -> Additional Boards Managers url_

Or download it on your local machine then in  _Preference_ set:
`file:\<path on your local machine\>\package_stm_index.json`

I removed the reference to the old F1 core because as the new one now include some F1 boards, this brought some lack of understanding. I'm currently working to merge BluePill and MappleMini.

**Comment by dackley1935** [comment]
Thanks you very much for the help. I really appreciate the quick response.

**Comment by fpistm** [comment]
You're welcome ;)
